# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - projs.md
  - comps.md
  - etc.md

footer: '<a href="">resume</a> / <a href="https://github.com/jpark621">github</a> / <a href="https://www.linkedin.com/in/jinspark621/">linkedin</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
